
export const CREATE_TODO = 'CREATE_TODO';
export const COMPLETE = 'COMPLETE';
export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const GET_COMPLETED_TODOS = 'GET_COMPLETED_TODOS';
export const GET_IN_PROGRESS_TODOS = 'GET_IN_PROGRESS_TODOS';
export const DELETE = 'DELETE';
export const FILTER_ALL_TODOS = 'FILTER_ALL_TODOS'
export const FILTER_ACTIVE_TODOS = 'FILTER_ACTIVE_TODOS'
export const FILTER_COMPLETED_TODOS = 'FILTER_COMPLETED_TODOS'
